name: Do the things
on:
  - push
  
permissions:
  contents: write
  packages: write

env:
  PACKAGE_NAME: helloworld
  SHORT_SHA: $(echo ${{ github.sha }}} | cut -c1-8)

jobs:
  maven-test:
    name: Maven Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Maven Testing
        run: |
          mvn clean test
          echo $0


  docker-build-and-push:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: maven-test
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      
      -
        name: Authenticate to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      -
        name: Build and Push Container
        run: | 
          docker context ls
          export branch=$(echo ${{ github.ref }} | sed 's/.*\///')
          #docker buildx inspect imagetools inspect 
          #docker buildx build \
          docker build \
          -q . \
          -t ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}:$branch \
          -t ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}:${{ env.SHORT_SHA }} \
          -t ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}:latest
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }} --all-tags
